### ISSUE TITLE
Fehlermeldung beim Bildupload

### ISSUE THREAD

**Issue by oppi85** [WI13-project/infosaeule#26]
wenn im upload Script kein Filename angegeben ist muss dieser Fehler abgefangen werden

**Comment by Niob07** [comment]
Bild-Upload mit Bildbeschreibung(getestet mit Firefox 33.1 und Safari 8.0.2(jeweils an einem Mac)) schlägt fehl.:

Warning: getimagesize() [function.getimagesize]: Filename cannot be empty in /users/ohli/www/wi13/wi13/prototyp2/check.php on line 116
Bitte Datei angeben!userid:3Bildname darf nicht leer sein!
