### ISSUE TITLE
Nutzerverwaltung checken

### ISSUE THREAD

**Issue by ohli** [WI13-project/infosaeule#28]
Warning: Unexpected character in input: ' in /users/ohli/www/wi13/wi13/prototyp2/form.php on line 101

Wenn ich als root die Nutzer verwalten will

**Comment by oppi85** [comment]
kanns sein das hier der fehler vom header kam?

**Comment by ohli** [comment]
Komisch, kann in der form.php nichts finden, lag wohl wirklich am Header. Ich schau nochmal.

**Comment by oppi85** [comment]
ich hatte den bootstrap.js hochgepackt, weil ich die nav zeile beim zusammenschieben verkleinern wollte. das hat nicht geklappt aber anscheinend is er dadurch mit unseren ids und klassen durcheinander gekommen. wer weiß, erstmal gehts ja wieder

**Comment by ohli** [comment]
Ok, läuft wieder!
Das wäre jetzt langsam die Gelegenheit zum branchen^^

http://git-scm.com/book/de/v1/Git-Branching
..so geht nichts kaputt und neue Funktionen können wenn sie funktionieren direkt wieder eingepflegt werden.
