### ISSUE TITLE
PNG Handeling - High Priority

### ISSUE THREAD

**Issue by zottelbeyer** [WI13-project/infosaeule#35]
Freunde der Sonne, wir haben ein Problem:

Mit PNGs kommt unser Projekt garnicht zurecht,
beim Uploaden gibt es nen Fehler, Thumbnail wird nicht erstellt und in der view.php wird es auch nicht angezeigt.

Bitte dringend bis Mittwoch fixen!

**Comment by ohli** [comment]
War nur n Typo. Danke fürs Testen!
..und geschlossen
