### ISSUE TITLE
Auto-Logout

### ISSUE THREAD

**Issue by zottelbeyer** [WI13-project/infosaeule#38]
Der automatische Logout blockiert den Zugang zur index.php.
Die (login.php) Seite wird nicht geladen, sondern nur die Fehlermeldung angezeigt.

Die sollte aber idealerweise nur kommen wenn man auf den Verwaltungsseiten ist. Ausserdem wäre ein forward auf die login.php nach der Meldung sinnvoll.

**Comment by ohli** [comment]
War ich schonmal dran, guck ich nochmal nach.
