### ISSUE TITLE
index.php Header Zeile

### ISSUE THREAD

**Issue by zottelbeyer** [WI13-project/infosaeule#39]
![snapshot1](https://cloud.githubusercontent.com/assets/3685916/5817248/2771fb76-a0aa-11e4-914a-7c2e7c1f1984.png)

Könnte man da bitte noch etwas mehr Platz zwischen dem Menü und der ersten Textzeile schaffen? Sieht nicht so schick aus.

**Comment by ohli** [comment]
Das liegt nicht zwangsläufig am Platz, sondern an der nicht vorhandenen Responsivität,  relates to #32
Wenn man's weiter skaliert ist das Menü komplett weg.

**Comment by zottelbeyer** [comment]
Das ist der Screenshot bei 1080p fullscreen...

**Comment by ohli** [comment]
:-(
Na denn ans Werk...
